[package]
name = "led"
version = "0.1.0"
authors = ["Bodo Kaiser <i@bodokaiser.io>"]
edition = "2018"

[dependencies]
panic-halt = "0.2.0"
cortex-m = "0.6.2"
cortex-m-rt = "0.6.12"
stm32f0xx-hal = {version = "0.15", features = ["stm32f072"]}

[profile.release]
lto = true
debug = true