[package]
name = "hello-world"
version = "0.1.0"
authors = ["Bodo Kaiser <i@bodokaiser.io>"]
edition = "2018"

[dependencies]
panic-halt = "0.2.0"
cortex-m-rt = "0.6.12"
cortex-m-semihosting = "0.3.5"

[profile.release]
lto = true
debug = true